version: '3'
networks:
  twitter_alert:
    external: false
    name: "twitter_alert"
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    networks:
      twitter_alert:
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
    ports:
      - "5432:5432"
    volumes:
      - ./dev_db:/var/lib/postgresql/data
  nextjs:
    image: node:latest
    container_name: nextjs
    restart: always
    environment:
      NODE_ENV: development
    networks:
      twitter_alert:
    ports:
      - "3001:3000"
      - "9999:5555"
    volumes:
      - ./:/app
    working_dir: /app
    command: "yarn dev"
    depends_on:
      - postgresql